name: "typeprof-action"
description: "GitHub Action for Ruby TypeProf"
author: "Masafumi Koba"
inputs:
  token:
    description: "GitHub token"
    required: true
  file:
    description: "Checked file(s). Glob is available."
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
