name: "typeprof-action"
description: "GitHub Action for Ruby TypeProf"
author: "Masafumi Koba"
inputs:
  file:
    description: "Analyzed files"
    required: false
    default: "**/*.rb"
  token:
    description: "GitHub token"
    required: true
runs:
  using: "node14"
  main: "dist/index.js"
