name: Smoke test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  valid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install typeprof
      - uses: ./
        with:
          file: test/smoke/valid.rb

  invalid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install typeprof
      - uses: ./
        with:
          file: test/smoke/invalid.rb
        continue-on-error: true

  bundler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle init
      - run: bundle add typeprof
      - uses: ./
        with:
          file: test/smoke/invalid*.rb
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  no-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install typeprof
      - uses: ./
        with:
          file: "*.rb"
