name: Smoke test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install typeprof
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: test/smoke/*.rb
        continue-on-error: true

  test-bundler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle init
      - run: bundle add typeprof
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: test/smoke/*.rb
        continue-on-error: true
