name: Smoke test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: test/smoke/*.rb
